In [1]:
import numpy as np

In [2]:
a = np.arange(10)
print(a)
b = a.reshape(5,2)

[0 1 2 3 4 5 6 7 8 9]


In [43]:
a.ndim

1

In [138]:
flip = np.random.randint(0,2,3)
print(flip)
h, _ = np.bincount(flip, minlength=2)
print(h,_)
print(h)

[0 1 1]
1 2
1


In [3]:
b.ndim


2

In [4]:
b.shape

(5, 2)

In [5]:
b.dtype.name

'int64'

In [6]:
b.size


10

In [7]:
type(b)

numpy.ndarray

In [19]:
ones = np.ones((3,4), dtype=np.int16)

In [27]:
c = np.arange(30)
print(c)
print(c[3:8])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[3 4 5 6 7]


In [32]:
c = c.reshape(5,6)
print(c)

c.ndim

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


2

In [41]:
d= c[1:3]
print(d)

d.ndim

[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


2

In [1]:
np.arange(10)**3

NameError: name 'np' is not defined